insert into Termekeks values ( 'Activity',	5590,	'Társasjáték', '/Content/Images/tarsas/Activity.png');
insert into Termekeks values ( 'Bang!',	3990,	'Kártyajáték', '/Content/Images/kartyak/Bang.png');
insert into Termekeks values ( 'Bejeweled',	7990,	'Társasjáték', '/Content/Images/tarsas/Bejeweled.png');
insert into Termekeks values ( 'Dobókocka szett',	1290,	'Kiegészítő', '/Content/Images/kiegek/dobokocka.png');
insert into Termekeks values ( 'DOS',	1190,	'Kártyajáték', '/Content/Images/kartyak/Dos.png');
insert into Termekeks values ( 'Limitált figurák',	1190,	'Kiegészítő', '/Content/Images/kiegek/figurak.png');
insert into Termekeks values ( 'Figuraszett',	450,	'Kiegészítő', '/Content/Images/kiegek/figuraszett.png');
insert into Termekeks values ( 'Honfoglaló',	7290,	'Társasjáték', '/Content/Images/tarsas/Honfoglalo.png');
insert into Termekeks values ( 'Kérdezz! Felelek',	990,	'Társasjáték', '/Content/Images/tarsas/Kerdezz_Felelek.png');
insert into Termekeks values ( 'Ki nevet a végén?',	2290,	'Társasjáték', '/Content/Images/tarsas/Ki_nevet_a_vegen.png');
insert into Termekeks values ( 'Kockamanók',	450,	'Kiegészítő', '/Content/Images/kiegek/kockamano.png');
insert into Termekeks values ( 'Korongok',	450,	'Kiegészítő', '/Content/Images/kiegek/korongok.png');
insert into Termekeks values ( 'KRESZ TESZT',	1690,	'Társasjáték', '/Content/Images/tarsas/Kresz_Teszt.png');
insert into Termekeks values ( 'Magyar Kártya',	990,	'Kártyajáték', '/Content/Images/kartyak/Magyar_Kartya.png');
insert into Termekeks values ( 'Magyar Népmesék',	8490,	'Kártyajáték', '/Content/Images/kartyak/Magyar_Nepmesek.png');
insert into Termekeks values ( 'Magyarország kvíz',	2590,	'Társasjáték', '/Content/Images/tarsas/Magyarorszag_kviz.png');
insert into Termekeks values ( 'Maradj Talpon!',	7690,	'Társasjáték', '/Content/Images/tarsas/Maradj_Talpon.png');
insert into Termekeks values ( 'Monopoly Budapest',	7990,	'Társasjáték', '/Content/Images/tarsas/Monopoly_Budapest.png');
insert into Termekeks values ( 'Póker Kártya',	990,	'Kártyajáték', '/Content/Images/kartyak/Poker.png');
insert into Termekeks values ( 'Sheriff',	9990,	'Társasjáték', '/Content/Images/tarsas/sheriff.png');
insert into Termekeks values ( 'Spongebob Monopoly',	6690,	'Társasjáték', '/Content/Images/tarsas/Spongebob_Monopoly.png');
insert into Termekeks values ( 'Sponsio',	5590,	'Kártyajáték', '/Content/Images/kartyak/Sponsio.png');
insert into Termekeks values ( 'Szerencskerék',	5590,	'Társasjáték', '/Content/Images/tarsas/Szerencsekerek.png');
insert into Termekeks values ( 'Tom & Jerry',	5590,	'Társasjáték', '/Content/Images/tarsas/Tom_es_Jerry.png');
insert into Termekeks values ( 'Twister',	5590,	'Társasjáték', '/Content/Images/tarsas/Twister.png');
insert into Termekeks values ( 'UNO',	5590,	'Kártyajáték', '/Content/Images/kartyak/Uno.png');
insert into Termekeks values ( 'Yu-Gi-Oh',	5590,	'Kártyajáték', '/Content/Images/kartyak/Yugioh.png');
insert into Termekeks values ( 'Zsetonok',	5590,	'Kiegészítő', '/Content/Images/kiegek/zsetonok.png');